const MAX_CELL_TEXT = 32000;

function buildAdminAuditWorkbook(exportData, options = {}) {
  const requests = exportData.requests || [];
  const events = exportData.events || [];
  const outboundEmails = exportData.outboundEmails || [];
  const definitions = exportData.definitions || [];
  const sheets = [
    {
      name: 'Summary',
      rows: summaryRows(exportData, options)
    },
    {
      name: 'Requests',
      rows: objectRowsToSheetRows(requestRows(requests), [
        'db_request_id',
        'db_process_type',
        'db_created_at',
        'db_updated_at',
        'requestId',
        'processType',
        'createdAt',
        'updatedAt',
        'status',
        'employeeName',
        'employeeEmail',
        'requesterEmail',
        'lineManagerEmail'
      ])
    },
    {
      name: 'Workflow History',
      rows: objectRowsToSheetRows(historyRows(requests), [
        'requestId',
        'processType',
        'historyField',
        'historyIndex',
        'at',
        'stepName',
        'stepType',
        'approverEmail',
        'decision',
        'comment',
        'recipients',
        'raw_entry_json'
      ])
    },
    {
      name: 'Events',
      rows: objectRowsToSheetRows(eventRows(events), [
        'id',
        'timestamp',
        'requestId',
        'actorEmail',
        'event',
        'raw_details_json'
      ])
    },
    {
      name: 'Outbound Emails',
      rows: objectRowsToSheetRows(emailRows(outboundEmails), [
        'id',
        'createdAt',
        'toEmail',
        'ccEmail',
        'subject',
        'provider_mode',
        'provider_accepted',
        'provider_rejected',
        'provider_messageId',
        'provider_deliveredAt',
        'bodyLength',
        'htmlBodyLength',
        'body',
        'htmlBody',
        'raw_provider_result_json'
      ])
    },
    {
      name: 'Definitions',
      rows: objectRowsToSheetRows(definitionRows(definitions), [
        'category',
        'definitionKey',
        'enabled',
        'source',
        'createdAt',
        'updatedAt',
        'data_name',
        'data_description',
        'raw_data_json'
      ])
    }
  ];
  return buildXlsxWorkbook(sheets);
}

function summaryRows(exportData, options) {
  return [
    ['Field', 'Value'],
    ['Export type', 'Admin audit export'],
    ['Generated at', exportData.generatedAt || new Date().toISOString()],
    ['Generated by', options.actorEmail || ''],
    ['Process key', options.processKey || exportData.processKey || ''],
    ['Process name', options.processName || ''],
    ['Requests', String((exportData.requests || []).length)],
    ['Workflow history rows', String(historyRows(exportData.requests || []).length)],
    ['Events', String((exportData.events || []).length)],
    ['Outbound emails', String((exportData.outboundEmails || []).length)],
    ['Definitions', String((exportData.definitions || []).length)],
    ['Sheets', 'Requests; Workflow History; Events; Outbound Emails; Definitions'],
    ['Notes', 'Cells that exceed Excel text limits are truncated in the workbook. Length columns are included where large message bodies are exported.']
  ];
}

function requestRows(records) {
  return (records || []).map(record => {
    const data = record.data || {};
    const row = {
      db_request_id: record.requestId || record.request_id || '',
      db_process_type: record.processType || record.process_type || '',
      db_created_at: record.createdAt || record.created_at || '',
      db_updated_at: record.updatedAt || record.updated_at || ''
    };
    Object.keys(data).sort().forEach(key => {
      row[key] = data[key];
    });
    row.raw_data_json = data;
    return row;
  });
}

function historyRows(records) {
  const rows = [];
  (records || []).forEach(record => {
    const data = record.data || {};
    [
      { field: 'approvalHistory', label: 'approval' },
      { field: 'finalApprovalHistory', label: 'finalApproval' },
      { field: 'changeHistory', label: 'change' }
    ].forEach(history => {
      parseJsonArray(data[history.field]).forEach((entry, index) => {
        const row = {
          requestId: data.requestId || record.requestId || record.request_id || '',
          processType: data.processType || record.processType || record.process_type || '',
          historyField: history.field,
          historyStage: history.label,
          historyIndex: index + 1,
          at: entry.at || entry.timestamp || '',
          stepName: entry.stepName || entry.requestedByName || '',
          stepType: entry.stepType || entry.type || '',
          approverEmail: entry.approverEmail || entry.requestedByEmail || entry.editedByEmail || '',
          decision: entry.decision || entry.type || '',
          comment: entry.comment || entry.requestComment || '',
          recipients: Array.isArray(entry.recipients) ? entry.recipients.join(', ') : '',
          raw_entry_json: entry
        };
        Object.keys(entry || {}).sort().forEach(key => {
          if (!Object.prototype.hasOwnProperty.call(row, key)) {
            row[`entry_${key}`] = entry[key];
          }
        });
        rows.push(row);
      });
    });
  });
  return rows;
}

function eventRows(records) {
  return (records || []).map(record => {
    const details = record.details || {};
    const row = {
      id: record.id,
      timestamp: record.timestamp,
      requestId: record.requestId,
      actorEmail: record.actorEmail,
      event: record.event,
      raw_details_json: details
    };
    addObjectFields(row, 'details', details);
    return row;
  });
}

function emailRows(records) {
  return (records || []).map(record => {
    const provider = record.providerResult || {};
    const body = record.body || '';
    const htmlBody = record.htmlBody || '';
    const row = {
      id: record.id,
      createdAt: record.createdAt,
      toEmail: record.toEmail,
      ccEmail: record.ccEmail,
      subject: record.subject,
      bodyLength: String(body.length),
      htmlBodyLength: String(htmlBody.length),
      body,
      htmlBody,
      raw_provider_result_json: provider
    };
    addObjectFields(row, 'provider', provider);
    return row;
  });
}

function definitionRows(records) {
  return (records || []).map(record => {
    const data = record.data || {};
    const row = {
      category: record.category,
      definitionKey: record.definitionKey,
      enabled: record.enabled,
      source: record.source,
      createdAt: record.createdAt,
      updatedAt: record.updatedAt,
      raw_data_json: data
    };
    addObjectFields(row, 'data', data);
    return row;
  });
}

function addObjectFields(row, prefix, value) {
  if (!value || typeof value !== 'object' || Array.isArray(value)) {
    return;
  }
  Object.keys(value).sort().forEach(key => {
    row[`${prefix}_${key}`] = value[key];
  });
}

function parseJsonArray(value) {
  if (Array.isArray(value)) {
    return value;
  }
  if (!value) {
    return [];
  }
  try {
    const parsed = typeof value === 'string' ? JSON.parse(value) : value;
    return Array.isArray(parsed) ? parsed : [];
  } catch (err) {
    return [];
  }
}

function objectRowsToSheetRows(rows, preferredColumns) {
  if (!rows.length) {
    return [['No rows']];
  }
  const columns = collectColumns(rows, preferredColumns || []);
  return [columns].concat(rows.map(row => columns.map(column => row[column])));
}

function collectColumns(rows, preferredColumns) {
  const seen = {};
  const columns = [];
  function add(column) {
    if (!column || seen[column]) {
      return;
    }
    seen[column] = true;
    columns.push(column);
  }
  preferredColumns.forEach(add);
  rows.forEach(row => {
    Object.keys(row).sort().forEach(add);
  });
  return columns;
}

function buildXlsxWorkbook(sheets) {
  const normalizedSheets = sheets.map((sheet, index) => ({
    name: sanitizeSheetName(sheet.name || `Sheet ${index + 1}`, index),
    rows: sheet.rows || []
  }));
  const files = [
    { name: '[Content_Types].xml', data: contentTypesXml(normalizedSheets) },
    { name: '_rels/.rels', data: rootRelsXml() },
    { name: 'xl/workbook.xml', data: workbookXml(normalizedSheets) },
    { name: 'xl/_rels/workbook.xml.rels', data: workbookRelsXml(normalizedSheets) },
    { name: 'xl/styles.xml', data: stylesXml() }
  ];
  normalizedSheets.forEach((sheet, index) => {
    files.push({
      name: `xl/worksheets/sheet${index + 1}.xml`,
      data: worksheetXml(sheet.rows)
    });
  });
  return zipFiles(files);
}

function worksheetXml(rows) {
  const normalizedRows = rows.length ? rows : [['No rows']];
  const maxColumns = normalizedRows.reduce((max, row) => Math.max(max, row.length), 1);
  const dimension = `A1:${columnName(maxColumns - 1)}${normalizedRows.length}`;
  const sheetRows = normalizedRows.map((row, rowIndex) => {
    const cells = [];
    for (let columnIndex = 0; columnIndex < maxColumns; columnIndex += 1) {
      cells.push(cellXml(row[columnIndex], rowIndex + 1, columnIndex, rowIndex === 0));
    }
    return `<row r="${rowIndex + 1}">${cells.join('')}</row>`;
  }).join('');
  return xmlHeader() +
    `<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">` +
    `<dimension ref="${dimension}"/>` +
    `<sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews>` +
    `<sheetFormatPr defaultRowHeight="15"/>` +
    `<cols><col min="1" max="${maxColumns}" width="24" customWidth="1"/></cols>` +
    `<sheetData>${sheetRows}</sheetData>` +
    `<autoFilter ref="${dimension}"/>` +
    `<pageMargins left="0.7" right="0.7" top="0.75" bottom="0.75" header="0.3" footer="0.3"/>` +
    `</worksheet>`;
}

function cellXml(value, rowNumber, columnIndex, header) {
  const ref = `${columnName(columnIndex)}${rowNumber}`;
  const style = header ? ' s="1"' : '';
  return `<c r="${ref}" t="inlineStr"${style}><is><t xml:space="preserve">${escapeXml(excelCellText(value))}</t></is></c>`;
}

function excelCellText(value) {
  if (value === undefined || value === null) {
    return '';
  }
  let text = typeof value === 'object' ? JSON.stringify(value) : String(value);
  text = text.replace(/\u0000/g, '');
  if (/^[=+\-@]/.test(text)) {
    text = `'${text}`;
  }
  if (text.length > MAX_CELL_TEXT) {
    return `${text.slice(0, MAX_CELL_TEXT)} [truncated ${text.length - MAX_CELL_TEXT} chars]`;
  }
  return text;
}

function columnName(index) {
  let name = '';
  let value = index + 1;
  while (value > 0) {
    const remainder = (value - 1) % 26;
    name = String.fromCharCode(65 + remainder) + name;
    value = Math.floor((value - 1) / 26);
  }
  return name;
}

function contentTypesXml(sheets) {
  return xmlHeader() +
    `<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">` +
    `<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>` +
    `<Default Extension="xml" ContentType="application/xml"/>` +
    `<Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>` +
    `<Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>` +
    sheets.map((sheet, index) => `<Override PartName="/xl/worksheets/sheet${index + 1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join('') +
    `</Types>`;
}

function rootRelsXml() {
  return xmlHeader() +
    `<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">` +
    `<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/>` +
    `</Relationships>`;
}

function workbookXml(sheets) {
  return xmlHeader() +
    `<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">` +
    `<sheets>` +
    sheets.map((sheet, index) => `<sheet name="${escapeXml(sheet.name)}" sheetId="${index + 1}" r:id="rId${index + 1}"/>`).join('') +
    `</sheets>` +
    `</workbook>`;
}

function workbookRelsXml(sheets) {
  return xmlHeader() +
    `<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">` +
    sheets.map((sheet, index) => `<Relationship Id="rId${index + 1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${index + 1}.xml"/>`).join('') +
    `<Relationship Id="rId${sheets.length + 1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>` +
    `</Relationships>`;
}

function stylesXml() {
  return xmlHeader() +
    `<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">` +
    `<fonts count="2"><font><sz val="11"/><name val="Calibri"/></font><font><b/><sz val="11"/><color rgb="FFFFFFFF"/><name val="Calibri"/></font></fonts>` +
    `<fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF021D49"/><bgColor indexed="64"/></patternFill></fill></fills>` +
    `<borders count="1"><border><left/><right/><top/><bottom/><diagonal/></border></borders>` +
    `<cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs>` +
    `<cellXfs count="2"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyFont="1" applyFill="1"/></cellXfs>` +
    `<cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles>` +
    `</styleSheet>`;
}

function xmlHeader() {
  return '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>';
}

function sanitizeSheetName(name, index) {
  const cleaned = String(name || `Sheet ${index + 1}`)
    .replace(/[\[\]\*\/\\\?:]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .slice(0, 31);
  return cleaned || `Sheet ${index + 1}`;
}

function escapeXml(value) {
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

const CRC_TABLE = makeCrcTable();

function zipFiles(files) {
  const localParts = [];
  const centralParts = [];
  let offset = 0;
  files.forEach(file => {
    const nameBuffer = Buffer.from(file.name, 'utf8');
    const dataBuffer = Buffer.isBuffer(file.data) ? file.data : Buffer.from(String(file.data), 'utf8');
    const crc = crc32(dataBuffer);
    const localHeader = Buffer.alloc(30);
    localHeader.writeUInt32LE(0x04034b50, 0);
    localHeader.writeUInt16LE(20, 4);
    localHeader.writeUInt16LE(0, 6);
    localHeader.writeUInt16LE(0, 8);
    localHeader.writeUInt16LE(0, 10);
    localHeader.writeUInt16LE(0, 12);
    localHeader.writeUInt32LE(crc, 14);
    localHeader.writeUInt32LE(dataBuffer.length, 18);
    localHeader.writeUInt32LE(dataBuffer.length, 22);
    localHeader.writeUInt16LE(nameBuffer.length, 26);
    localHeader.writeUInt16LE(0, 28);
    localParts.push(localHeader, nameBuffer, dataBuffer);

    const centralHeader = Buffer.alloc(46);
    centralHeader.writeUInt32LE(0x02014b50, 0);
    centralHeader.writeUInt16LE(20, 4);
    centralHeader.writeUInt16LE(20, 6);
    centralHeader.writeUInt16LE(0, 8);
    centralHeader.writeUInt16LE(0, 10);
    centralHeader.writeUInt16LE(0, 12);
    centralHeader.writeUInt16LE(0, 14);
    centralHeader.writeUInt32LE(crc, 16);
    centralHeader.writeUInt32LE(dataBuffer.length, 20);
    centralHeader.writeUInt32LE(dataBuffer.length, 24);
    centralHeader.writeUInt16LE(nameBuffer.length, 28);
    centralHeader.writeUInt16LE(0, 30);
    centralHeader.writeUInt16LE(0, 32);
    centralHeader.writeUInt16LE(0, 34);
    centralHeader.writeUInt16LE(0, 36);
    centralHeader.writeUInt32LE(0, 38);
    centralHeader.writeUInt32LE(offset, 42);
    centralParts.push(centralHeader, nameBuffer);
    offset += localHeader.length + nameBuffer.length + dataBuffer.length;
  });

  const centralDirectory = Buffer.concat(centralParts);
  const end = Buffer.alloc(22);
  end.writeUInt32LE(0x06054b50, 0);
  end.writeUInt16LE(0, 4);
  end.writeUInt16LE(0, 6);
  end.writeUInt16LE(files.length, 8);
  end.writeUInt16LE(files.length, 10);
  end.writeUInt32LE(centralDirectory.length, 12);
  end.writeUInt32LE(offset, 16);
  end.writeUInt16LE(0, 20);
  return Buffer.concat(localParts.concat([centralDirectory, end]));
}

function makeCrcTable() {
  const table = new Uint32Array(256);
  for (let index = 0; index < 256; index += 1) {
    let value = index;
    for (let bit = 0; bit < 8; bit += 1) {
      value = value & 1 ? 0xedb88320 ^ (value >>> 1) : value >>> 1;
    }
    table[index] = value >>> 0;
  }
  return table;
}

function crc32(buffer) {
  let crc = 0xffffffff;
  for (let index = 0; index < buffer.length; index += 1) {
    crc = CRC_TABLE[(crc ^ buffer[index]) & 0xff] ^ (crc >>> 8);
  }
  return (crc ^ 0xffffffff) >>> 0;
}

module.exports = {
  buildAdminAuditWorkbook
};
